version: '3.8'

networks:
  video-net:
    driver: bridge

services:
  srs:
    image: ossrs/srs:5
    container_name: srs-hls
    command: ["./objs/srs", "-c", "conf/srs.conf"]
    ports:
      - "1935:1935"      # RTMP for input
      - "10080:10080/udp"  # SRT for analysis input
    volumes:
      - ./srs-hls-platform/srs/srs.conf:/usr/local/srs/conf/srs.conf
      # Volume para compartilhar os arquivos HLS com o Nginx
      - ./srs-hls-platform/web/html:/usr/local/srs/objs/nginx/html
    networks:
      - video-net
    restart: always

  video-analysis:
    build:
      context: ./video-analysis-pipeline
      dockerfile: Dockerfile
    container_name: video-analysis
    depends_on:
      - srs
    environment:
      # Disable NUMA memory policy optimizations to avoid set_mempolicy errors in VPS
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - NUMBA_NUM_THREADS=1
      - OMP_PROC_BIND=false
      - KMP_AFFINITY=disabled
    # Additional security options for VPS if environment variables don't work
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    command: 
      - python3
      - scripts/main.py
      - --config-path
      - "/app/config.json"
      - --model-path
      - "/app/models/mobilenet_ssd_quantized.onnx"
      - --input-uri
      - "http://srs:8080/live/livestream.m3u8"
      - --srt-output-uri
      - "srt://srs:10080?streamid=#!::r=live/processed"
    networks:
      - video-net
    restart: always

  web:
    image: nginx:1.25
    container_name: nginx-web
    ports:
      - "8081:80"        # Porta HTTP para o player web e entrega HLS
    volumes:
      - ./srs-hls-platform/web/html:/usr/share/nginx/html
      - ./srs-hls-platform/web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - video-net
    depends_on:
      - srs
    restart: always
